name: Create qualification reports

on:
  workflow_dispatch:
    inputs:
      commit-message:
        required: false
        type: string
        default: 'VN.N Update N'

permissions:
  contents: write
  pull-requests: write
  
env:
  WORKING_DIR: 'D:/0'
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  read_inputs:
    runs-on: ubuntu-latest
    outputs:
      tools_table: ${{ steps.tools_table.outputs.tools-table }}
      pk_sim_version: ${{ steps.tools_table.outputs.pk-sim }}
      qualification_framework_version: ${{ steps.tools_table.outputs.qualification-framework }}
      qualifications_table: ${{ steps.qualifications_table.outputs.table }}
      qualifications: ${{steps.qualifications.outputs.data}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - id: tools_table
      name: Get tools table
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/get-tools-versions@main
      with:
        tools-path: tools.csv

    - id: install-r
      name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'latest'
        use-public-rspm: true
        
    - name: Read and export qualifications as json
      run: |
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e '
        qualificationsData <- read.csv("qualifications.csv", check.names = FALSE, stringsAsFactors = FALSE, colClasses = c("logical", rep("character", 4)))
        cat(jsonlite::toJSON(qualificationsData[qualificationsData$Execute, ], dataframe = "rows"))
        ' > qualifications.json
      shell: bash
    
    - name: Output qualifications data for table conversion
      id: qualifications_data
      run: echo "json=$(cat qualifications.json)" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Markdown table for qualifications
      uses: buildingcash/json-to-markdown-table-action@v1 
      id: qualifications_table
      with: 
        json: "${{ steps.qualifications_data.outputs.json }}"
        
    - name: Set qualifications data as output for matrix run strategy
      id: qualifications
      run: echo "data={\"include\":$(cat qualifications.json)}" >> $GITHUB_OUTPUT
      shell: bash
  
  qualification:
    needs: read_inputs
    strategy:
      matrix: ${{ fromJSON(needs.read_inputs.outputs.qualifications) }}
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Rebase from main
      run: |
        git config --global core.longpaths true
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b ${{ matrix['Repository name'] }}-${{ github.run_number }}
        git push -u origin ${{ matrix['Repository name'] }}-${{ github.run_number }}
        git fetch origin main
        git rebase -Xours origin/main
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          git reset HEAD^
        else
          echo "No parent commit for HEAD. Skipping reset."
        fi
        [ -d "${{ matrix['Folder name'] }}" ] && rm -rf ${{ matrix['Folder name'] }}/*
        git add ${{ matrix['Folder name'] }} || echo "No file in ${{ matrix['Folder name'] }}"
        git commit -m "Update ${{ matrix['Folder name'] }}" || echo "No changes to commit"
      shell: bash

    - id: qualification-environment
      name: Setup Qualification Environment
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/setup-qualification-environment@main
      with:
        tools-path: tools.csv

    - name: Downgrade ggplot2 to 3.5.2
      run: |
        Rscript -e 'remove.packages("ggplot2")'
        Rscript -e 'remotes::install_version("ggplot2", version = "3.5.2", repos = "https://cran.r-project.org")'
      shell: bash

    - name: Monitor Runner Resource Usage
      # Use bash to launch the PowerShell script in the background
      shell: bash
      run: |
        # Define the PowerShell script as a multi-line string in bash
        pwsh_script='
          $logFile = "C:\actions_runner\_work\runner_stats.log"
          echo "Starting resource monitoring. Logging to $logFile and STDOUT."

          while ($true) {
            try {
              # Get the Runner.Listener process, which is the main agent process
              $runnerProcess = Get-Process -Name "Runner.Listener" -ErrorAction Stop
          
              # Get CPU usage for that specific process instance
              $cpuCounter = (Get-Counter -Counter "\Process($($runnerProcess.ProcessName))\ID Process" -InstanceName "$($runnerProcess.Id)").CounterSamples.CookedValue
              $cpuUsage = (Get-Counter -Counter "\Process($($runnerProcess.ProcessName))\% Processor Time" -InstanceName "$($runnerProcess.Id)").CounterSamples.CookedValue
          
              $mem = $runnerProcess.WorkingSet64 / 1MB
          
              $date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              $line = "$date -- Runner.Listener (PID: $($runnerProcess.Id)) -- CPU: $($cpuUsage.ToString('F2'))%, Memory: $($mem.ToString('F2')) MB"
          
              # Write to the GHA live log
              Write-Output $line
          
              # Also write to the log file for the artifact
              Add-Content -Path $logFile -Value $line
            }
            catch {
              # Handle cases where the process might not be found immediately or disappears
              $date = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
              $errorLine = "$date -- Could not find Runner.Listener process. It may have been terminated."
              Write-Output $errorLine
              Add-Content -Path $logFile -Value $errorLine
            }
        
            Start-Sleep -Seconds 5
          }
        '
    
        # Execute the PowerShell script in the background using pwsh
        # The output will be streamed to this step's log
        pwsh -Command "$pwsh_script" &

    - id: run-qualification
      name: Run qualification
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/report-evaluation@main
      with:
          model-repo: ${{ matrix['Repository name'] }}
          model-version: ${{ matrix['Released version'] }}
          folder-name: ${{ matrix['Folder name'] }}
          snapshot: ''
          evaluation: 'false'
          workflow-script: ${{ matrix['Workflow name'] }}
          pk-sim-version: ${{ needs.read_inputs.outputs.pk_sim_version }}
          qualification-framework-version: ${{ needs.read_inputs.outputs.qualification_framework_version }}
          save-model-file: 'false'
          save-pdf: 'true'
          run-directory: ${{ env.WORKING_DIR }}

    - name: Upload Resource Logs
      if: always() # This ensures the logs are uploaded even if the R step fails
      uses: actions/upload-artifact@v4
      with:
        name: runner-resource-logs
        path: C:\actions_runner\_work\runner_stats.log
    
    - id: copy-to-workspace
      name: Copy back to workspace and clean working directory before PR
      run: |
        file.copy(
          list.files("${{ env.WORKING_DIR }}", full.names = TRUE), 
          normalizePath(Sys.getenv("GITHUB_WORKSPACE"), winslash = "/"),
          recursive = TRUE
          )
        unlink("${{ env.WORKING_DIR }}", recursive = TRUE)
      shell: Rscript {0}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        # Use a custom PAT because GITHUB_TOKEN cannot trigger subsequent workflows (here: required checks on pull_request).
        # S. https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
#        token: ${{ secrets.PAT_PR_TRIGGERED_BY_ACTIONS }}
        branch: ${{ matrix['Repository name'] }}-${{ github.run_number }}
        base: main
        commit-message: ${{ inputs.commit-message }}
        add-paths: |
            ${{ matrix['Folder name'] }}/images/**
            ${{ matrix['Folder name'] }}/report.pdf
            ${{ matrix['Folder name'] }}/report.md
        title: Update Qualification Report for ${{ matrix['Folder name'] }}
        body: |
          ## Tools
          ${{ needs.read_inputs.outputs.tools_table }}
          ## Qualification plans
          ${{ needs.read_inputs.outputs.qualifications_table }}
#        reviewers: ${{ github.actor }}
        
