name: Test Cache

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

env:
  WORKING_DIR: 'D:/0'
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  read_inputs:
    runs-on: ubuntu-latest
    outputs:
      tools_table: ${{ steps.tools_table.outputs.tools-table }}
      pk_sim_version: ${{ steps.tools_table.outputs.pk-sim }}
      qualification_framework_version: ${{ steps.tools_table.outputs.qualification-framework }}
      models_table: ${{ steps.models_table.outputs.table }}
      models: ${{ steps.models.outputs.data }}
      first_model_repo: ${{ steps.first_model.outputs.first_repo }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - id: tools_table
      name: Get tools table
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/get-tools-versions@main
      with:
        tools-path: tools.csv

    - id: install-r
      name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'latest'
        use-public-rspm: true
    
    - name: Read and export models as json
      run: |
        Rscript -e 'install.packages("jsonlite")'
        Rscript -e '
          modelsData <- read.csv("models.csv", check.names = FALSE, stringsAsFactors = FALSE,
                                 colClasses = c("logical", rep("character", 6)))
          filtered <- modelsData[modelsData$Execute, ]
          cat(jsonlite::toJSON(filtered, dataframe = "rows"))
        ' > models.json
      shell: bash
    
    - name: Output models data for table conversion
      id: models_data
      run: echo "json=$(cat models.json)" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Markdown table for models
      uses: buildingcash/json-to-markdown-table-action@v1
      id: models_table
      with:
        json: "${{ steps.models_data.outputs.json }}"
    
    - name: Set models data as output for matrix run strategy
      id: models
      run: echo "data={\"include\":$(cat models.json)}" >> $GITHUB_OUTPUT
      shell: bash

  evaluation:
    needs: read_inputs
    strategy:
      matrix: ${{ fromJSON(needs.read_inputs.outputs.models) }}
      fail-fast: false
    runs-on: windows-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/RLibrary
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Compute tools.csv hash
      id: compute-tools-hash
      shell: bash
      run: echo "TOOLS_CSV_HASH=${{ hashFiles('tools.csv') }}" >> $GITHUB_ENV

    - name: Restore setup cache
      id: cache-setup
      uses: actions/cache@v4
      with:
        key: SingleAction-ospsuite-${{ env.TOOLS_CSV_HASH }}
        path: |
          ${{ env.R_LIBS_USER }}
          ${{ github.workspace }}/PK-Sim
          ${{ github.workspace }}/QualificationRunner

    - id: get-tools-versions
      name: Get tools versions (for R setup on cached runs)
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/get-tools-versions@main
      with:
        tools-path: tools.csv

    - name: Setup R (cached run)
      if: steps.cache-setup.outputs.cache-hit == 'true'
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '${{ steps.get-tools-versions.outputs.r }}'
        use-public-rspm: true

    - name: Setup Pandoc (cached run)
      if: steps.cache-setup.outputs.cache-hit == 'true'
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install chromehtml2pdf (cached run)
      if: steps.cache-setup.outputs.cache-hit == 'true'
      run: npm install -g chromehtml2pdf
      shell: bash

    - id: qualification-environment
      name: Setup Qualification Environment
      if: steps.cache-setup.outputs.cache-hit != 'true'
      uses: Open-Systems-Pharmacology/Workflows/.github/actions/setup-qualification-environment@main
      with:
        tools-path: tools.csv
        
