name: Test Cache

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
        echo "Don't run from the main branch"
      shell: bash
